### ISSUE TITLE
[PE-D][Tester E] Edit function executed despite error saying item would be not updated.

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-W12-3/tp#173]
Error thrown prints "Specified will not be updated" which suggests program will not update the edit user input. However, upon checking the list, it seem to be updated despite the printed message.

Additionally, as reported in the earlier issues, the edit functionality throws the wrong error despite following the format and inputting the correct type.

Before edit command:

![image.png](https://raw.githubusercontent.com/yixuann02/ped/main/files/a3321950-c52f-4c34-9951-6089aee23b67.png)

After edit command:

![image.png](https://raw.githubusercontent.com/yixuann02/ped/main/files/ab2a8b6a-193a-46ba-b573-ad3b8515807f.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: yixuann02/ped#12

**Comment by ngkaiwen123** [comment]
No longer causes this issue. List will not be updated if the input is wrong. Correct error message also printed now. Reason why this happens initially is because program detected "p/0}" which contains the "}" string, causing the error. 
![image](https://user-images.githubusercontent.com/88386677/229338451-cfe83e37-f1de-4174-9639-c8c7005986a0.png)
As you can see, `Cat` with upc code of `1111` is not updated.
Noticed that the initial command also caused name to change from `Cat` to `{capybara`, which is due to code using .contains() instead of using .startsWith() method. Code is also changed to resolve this issue.
